version: "3"

services:
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1:80
      SERVERNAME: vladino.me
      EXTRANAMES: www.vladino.me
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
