version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./custom_nginx_configuration.conf:/etc/nginx/conf.d/custom_nginx_configuration.conf:ro
    networks:
      - proxy

networks:
  proxy:
    external: false
