version: '3'

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hazarder
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - nginxdb_proxy

networks:
  nginxdb_proxy:
    external: true
